[versions]
grails = '6.1.1'
grails-gradle-plugin = '6.1.1'
grails-views = '3.1.2'
groovy-doc = '1.0.1'
nexus-publish-gradle-plugin = '1.3.0'

[libraries]
grails-gradle-plugin = { module = 'org.grails:grails-gradle-plugin', version.ref = 'grails-gradle-plugin' }
grails-views-gradle-plugin = { module = 'org.grails.plugins:views-gradle', version.ref = 'grails-views' }
nexus-publish-gradle-plugin = { module = 'io.github.gradle-nexus:publish-plugin', version.ref = 'nexus-publish-gradle-plugin' }
groovydoc-gradle-plugin = { module = 'io.github.groovylang.groovydoc:groovydoc-gradle-plugin', version.ref = 'groovy-doc' }
grails-docs = { module = 'org.grails:grails-docs', version.ref = 'grails' }
